// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {database} from '../models';
import {config} from '../models';

export function CheckForUpdates():Promise<main.UpdateCheckResult>;

export function CheckInternetConnection():Promise<boolean>;

export function CloseServer():Promise<void>;

export function DeleteServer(arg1:boolean):Promise<main.DeleteResult>;

export function DownloadJava(arg1:number):Promise<void>;

export function FilterNewerVersions(arg1:Array<string>,arg2:string):Promise<Array<string>>;

export function GetActiveServer():Promise<database.ServerRecord>;

export function GetAllServers():Promise<Array<database.ServerRecord>>;

export function GetConsoleHistory():Promise<string>;

export function GetCurrentVersion():Promise<string>;

export function GetDashboardData():Promise<main.DashboardData>;

export function GetDownloadURL():Promise<string>;

export function GetInstalledJavas():Promise<Array<main.JavaRuntimeInfo>>;

export function GetJVMConfig():Promise<main.JVMConfig>;

export function GetJavaDownloadOptions():Promise<Array<main.JavaDownloadOption>>;

export function GetLastServerPath():Promise<string>;

export function GetRecentServers():Promise<Array<database.ServerRecord>>;

export function GetServerProperties():Promise<Array<main.PropertyEntry>>;

export function GetSettings():Promise<config.Settings>;

export function GetVersions(arg1:string):Promise<Array<string>>;

export function InstallServer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function IsServerRunning():Promise<boolean>;

export function OpenServer(arg1:string):Promise<database.ServerRecord>;

export function OpenServerFolder():Promise<void>;

export function ReinstallServer(arg1:string):Promise<void>;

export function RestartServer():Promise<void>;

export function SaveJVMConfig(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SaveServerJava(arg1:string):Promise<void>;

export function SaveServerProperties(arg1:Array<main.PropertyEntry>):Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function SelectFolder():Promise<string>;

export function SendCommand(arg1:string):Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;

export function UpdateServer(arg1:string):Promise<void>;
