// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CheckInternetConnection() {
  return window['go']['main']['App']['CheckInternetConnection']();
}

export function CloseServer() {
  return window['go']['main']['App']['CloseServer']();
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DownloadJava(arg1) {
  return window['go']['main']['App']['DownloadJava'](arg1);
}

export function FilterNewerVersions(arg1, arg2) {
  return window['go']['main']['App']['FilterNewerVersions'](arg1, arg2);
}

export function GetActiveServer() {
  return window['go']['main']['App']['GetActiveServer']();
}

export function GetAllServers() {
  return window['go']['main']['App']['GetAllServers']();
}

export function GetConsoleHistory() {
  return window['go']['main']['App']['GetConsoleHistory']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetDashboardData() {
  return window['go']['main']['App']['GetDashboardData']();
}

export function GetDownloadURL() {
  return window['go']['main']['App']['GetDownloadURL']();
}

export function GetInstalledJavas() {
  return window['go']['main']['App']['GetInstalledJavas']();
}

export function GetJVMConfig() {
  return window['go']['main']['App']['GetJVMConfig']();
}

export function GetJavaDownloadOptions() {
  return window['go']['main']['App']['GetJavaDownloadOptions']();
}

export function GetLastServerPath() {
  return window['go']['main']['App']['GetLastServerPath']();
}

export function GetRecentServers() {
  return window['go']['main']['App']['GetRecentServers']();
}

export function GetServerProperties() {
  return window['go']['main']['App']['GetServerProperties']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersions(arg1) {
  return window['go']['main']['App']['GetVersions'](arg1);
}

export function InstallServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallServer'](arg1, arg2, arg3);
}

export function IsServerRunning() {
  return window['go']['main']['App']['IsServerRunning']();
}

export function OpenServer(arg1) {
  return window['go']['main']['App']['OpenServer'](arg1);
}

export function OpenServerFolder() {
  return window['go']['main']['App']['OpenServerFolder']();
}

export function ReinstallServer(arg1) {
  return window['go']['main']['App']['ReinstallServer'](arg1);
}

export function RestartServer() {
  return window['go']['main']['App']['RestartServer']();
}

export function SaveJVMConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveJVMConfig'](arg1, arg2, arg3, arg4);
}

export function SaveServerJava(arg1) {
  return window['go']['main']['App']['SaveServerJava'](arg1);
}

export function SaveServerProperties(arg1) {
  return window['go']['main']['App']['SaveServerProperties'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SendCommand(arg1) {
  return window['go']['main']['App']['SendCommand'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function UpdateServer(arg1) {
  return window['go']['main']['App']['UpdateServer'](arg1);
}
